@extends('layouts.site', ['title' => __('lexi.meta.profile.title'), 'description' => __('lexi.meta.profile.description'), 'robots' => 'noindex', 'bodyAttributes' => 'data-server-profile="true"'])

@section('content')
<main id="mainContent" class="profile-main">
  <div class="profile-hero"><div class="profile-avatar" id="profileAvatar">{{ strtoupper(mb_substr($user->name, 0, 1)) }}</div><div class="profile-hero-info"><div class="profile-name-wrap"><h1 class="profile-name" id="profileName">{{ $user->name }}</h1><button class="profile-edit-btn" id="btnEditName" aria-label="{{ __('lexi.profile.edit_name') }}"><i class="bi bi-pencil"></i></button></div><p class="profile-since" id="profileSince">{{ __('lexi.profile.member_since', ['date' => optional($user->created_at)->translatedFormat('F Y')]) }}</p><a href="{{ route('progreso') }}" class="profile-progress-link"><i class="bi bi-bar-chart-fill"></i> {{ __('lexi.profile.view_progress') }}</a></div></div>
  <section class="profile-section"><h2 class="profile-section-title">{{ __('lexi.profile.account_information') }}</h2><div class="profile-settings-card">@if (session('status'))<div class="alert alert-success mb-3">{{ session('status') }}</div>@endif @if ($errors->any())<div class="alert alert-danger mb-3">{{ $errors->first() }}</div>@endif <form method="POST" action="{{ route('profile.update') }}">@csrf<div class="profile-setting-row"><span class="profile-setting-label">{{ __('lexi.profile.username') }}</span><div class="profile-setting-control"><span class="profile-setting-value" id="displayName">{{ $user->name }}</span><button class="btn btn-outline-secondary btn-sm" type="button" id="btnEditName2">{{ __('lexi.common.edit') }}</button></div></div><div class="profile-setting-row" id="editNameRow" hidden><label class="profile-setting-label" for="inputName">{{ __('lexi.profile.new_name') }}</label><div class="profile-setting-control"><input class="profile-input" type="text" id="inputName" name="name" maxlength="30" value="{{ old('name', $user->name) }}" placeholder="{{ __('lexi.auth.name_placeholder') }}"><button class="btn btn-primary btn-sm" id="btnSaveName" type="submit">{{ __('lexi.common.save') }}</button><button class="btn btn-outline-secondary btn-sm" id="btnCancelName" type="button">{{ __('lexi.common.cancel') }}</button></div></div><div class="profile-setting-row"><span class="profile-setting-label">{{ __('lexi.profile.email') }}</span><div class="profile-setting-control"><span class="profile-setting-value">{{ $user->email }}</span><span class="profile-verified-badge"><i class="bi bi-patch-check-fill"></i> {{ $user->email_verified_at ? __('lexi.profile.verified') : __('lexi.profile.pending') }}</span></div></div><div class="profile-setting-row"><span class="profile-setting-label">{{ __('lexi.profile.native_language') }}</span><div class="profile-setting-control"><span class="profile-setting-value">{{ $languages[$user->mother_tongue_code] ?? strtoupper((string) $user->mother_tongue_code) }}</span><span class="profile-setting-hint">{{ __('lexi.profile.native_language_hint') }}</span></div></div></form><div class="profile-setting-row" style="flex-direction:column;align-items:stretch;gap:0.75rem"><span class="profile-setting-label">{{ __('lexi.profile.studied_languages') }}</span><div id="langChips" class="profile-studied-list">@forelse ($user->userLanguages as $userLanguage)<div class="profile-studied-row{{ $userLanguage->is_active ? ' is-active' : '' }}"><div class="profile-studied-left"><span>{{ $languages[$userLanguage->language_code] ?? strtoupper($userLanguage->language_code) }}</span></div>@if ($userLanguage->is_active)<span class="profile-studied-badge"><i class="bi bi-check-circle-fill"></i> {{ __('lexi.profile.active') }}</span>@endif</div>@empty<span class="profile-setting-hint" style="font-style:italic">{{ __('lexi.profile.no_studied_languages') }}</span>@endforelse</div></div></div></section>
  <section class="profile-section"><h2 class="profile-section-title">{{ __('lexi.profile.session') }}</h2><div class="profile-settings-card"><div class="profile-setting-row"><span class="profile-setting-label">{{ __('lexi.profile.active_session') }}</span><form method="POST" action="{{ route('logout') }}">@csrf<button class="btn btn-outline-secondary btn-sm" type="submit">{{ __('lexi.profile.logout') }}</button></form></div></div></section>
  <section class="profile-section"><h2 class="profile-section-title" style="color:#dc3545">{{ __('lexi.profile.danger_zone') }}</h2><div class="profile-settings-card profile-danger-card"><div class="profile-setting-row profile-setting-danger"><div><span class="profile-setting-label">{{ __('lexi.profile.delete_account') }}</span><p class="profile-setting-hint">{{ __('lexi.profile.delete_account_hint') }}</p></div><form method="POST" action="{{ route('profile.destroy') }}" onsubmit="return confirm('{{ __('lexi.profile.delete_account_confirm') }}');">@csrf @method('DELETE')<button class="btn btn-danger btn-sm" type="submit">{{ __('lexi.profile.delete_account') }}</button></form></div></div></section>
</main>
@endsection

@section('inlineScripts')
<script> (function(){const showEdit=(show)=>{document.getElementById('editNameRow').hidden=!show;document.querySelectorAll('[id="btnEditName"],[id="btnEditName2"]').forEach(b=>b.hidden=show);if(show){document.getElementById('inputName').focus();}}; document.getElementById('btnEditName').addEventListener('click',()=>showEdit(true));document.getElementById('btnEditName2').addEventListener('click',()=>showEdit(true));document.getElementById('btnCancelName').addEventListener('click',()=>showEdit(false));})(); </script>
@endsection